"""add ai_summary column

Revision ID: 3f534991920f
Revises: 5efa879b285c
Create Date: 2026-04-24 18:51:33.189878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f534991920f'
down_revision: Union[str, Sequence[str], None] = '5efa879b285c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_uploads', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_uploads', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
