"""permission and roles table creation and user table modify by adding role_id

Revision ID: 8298d9e4567c
Revises: d6d36d9e4b2c
Create Date: 2026-04-25 14:51:26.794031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8298d9e4567c'
down_revision: Union[str, Sequence[str], None] = 'd6d36d9e4b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'description')
    # ### end Alembic commands ###
