"""add file_path to data_uploads

Revision ID: 83d774701b91
Revises: 5e981965335a
Create Date: 2026-04-23 21:48:04.572853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d774701b91'
down_revision: Union[str, Sequence[str], None] = '5e981965335a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_uploads', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_index(op.f('ix_data_uploads_error_message'), table_name='data_uploads')
    op.drop_column('data_uploads', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_uploads', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_data_uploads_error_message'), 'data_uploads', ['error_message'], unique=False)
    op.drop_column('data_uploads', 'file_path')
    # ### end Alembic commands ###
