"""add ai_summary column

Revision ID: feef42d5b2a2
Revises: 17373bef8a35
Create Date: 2026-04-24 18:12:26.115398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feef42d5b2a2'
down_revision: Union[str, Sequence[str], None] = '17373bef8a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_uploads', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_uploads', 'ai_summary')
    # ### end Alembic commands ###
